homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  
  customize: !include customize.yaml         

# Enables the frontend
frontend:

#add hassio settings
hassio:

#add config to UI
config:


recorder:
  purge_keep_days: 3

#HTTP
http:
  api_password: !secret http_password 
  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #trusted_networks:
  #  - 192.168.1.0/24
  #ip_ban_enabled: True
  #login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#show map
map:

# Expose Alexa
emulated_hue:
  host_ip: 192.168.1.3
  exposed_domains:
    - media_player
    - script
    - switch
    
#Philips Hue
hue:
  bridges:
    - host: 192.168.1.14   
    
    
# Text to speech
tts:
  platform: google
  
mqtt:
  broker: !secret mqtt_broker
  port: 19532
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  
notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api
    
camera:
  platform: foscam
  ip: 192.168.1.16
  username: !secret foscam_username
  password: !secret foscam_password
  name: foscam


########################
#                                                  #
#                Includes                  #
#                                                  #
########################
  
switch: !include switch.yaml
script: !include_dir_named scripts 
device_tracker: !include device_trackers.yaml
sensor: !include sensor.yaml
media_player: !include media_players.yaml
weblink: !include weblinks.yaml
group: !include groups.yaml
automation: !include automations.yaml
input_boolean: !include input_boolean.yaml

#calendar:
  #- platform: todoist
    #token: 45ac7f0ad16a40dc752635f00d4af7a73cb79c63
    #custom_projects:
     #- name: 'Alexa Shopping List'
    
