homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  
  customize: !include customize.yaml         

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

#add hassio settings
hassio:

#add config to UI
config:

#add system health to UI
system_health:

#logs
recorder:
  purge_keep_days: 3

#HTTP
http:
  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3
  server_port: 443

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#show map
map:

# # Expose Alexa
# emulated_hue:
#   host_ip: 192.168.1.52
#   listen_port: 80
#   exposed_domains:
#     - media_player
#     - script
#     - switch
#     - light
#     - group
    
#Philips Hue
hue:
  bridges:
    - host: 192.168.1.14   
    
    
# Text to speech
tts:
  platform: google_translate
  cache: true
  time_memory: 300
  base_url: https://k-2.duckdns.org
  service_name: google_translate_say

#MQTT
#mqtt:
#  broker: !secret mqtt_broker
#  port: 19532
#  client_id: home-assistant-1
#  keepalive: 60
#  username: !secret mqtt_username
#  password: !secret mqtt_password

#PushBullet
notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api

#Camera    
camera:
  platform: foscam
  ip: 192.168.1.62
  username: !secret foscam_username
  password: !secret foscam_password
  name: foscam


########################
#                                                  #
#                Includes                  #
#                                                  #
########################
  
switch: !include switch.yaml
script: !include_dir_named scripts 
device_tracker: !include device_trackers.yaml
sensor: !include sensor.yaml
media_player: !include media_players.yaml
weblink: !include weblinks.yaml
group: !include groups.yaml
automation: !include automations.yaml
input_boolean: !include input_boolean.yaml
zone: !include zones.yaml
scene: !include scenes.yaml

#assistant     
google_assistant:
  project_id: smart-home-5432a
  service_account: !include service_account.json
  report_state: true
  #access_token: nRqdHZFILlcLpKWL
  #agent_user_id: [a string to identify user]
  #api_key: !secret google_api
  #entity_config:
    #switch.kitchen:
      #name: Custom Name for Google Assistant
      #aliases:
        #- bright lights
        #- entry lights
    #light.living_room:
      #expose: false
      #room: living room
    
#speedtest    
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

person:

# ring:
#   username: !secret ring_username
#   password: !secret ring_password